Blog5_t2/Blog5_t2/Models/Tag.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Blog5_t2.Models
{
    public class Tag
    {
        public int ID { set; get; }
        [Required]
        [StringLength(100, ErrorMessage = "10-100 ky tu", MinimumLength = 10)]
        public String Content { set; get; }
        public virtual ICollection<Post> Posts { set; get; }
    }
}

Blog5_t2/Blog5_t2/Controllers/PostsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Blog5_t2.Models;

namespace Blog5_t2.Controllers
{
    [Authorize]
    public class PostsController : Controller
    {
        
        private BlogDbContext db = new BlogDbContext();

        //
        // GET: /Posts/
        [AllowAnonymous]

        public ActionResult Index()
        {
            var posts = db.Posts.Include(p => p.UserProfile);
            return View(posts.ToList());
        }

        //
        // GET: /Posts/Details/5
        [AllowAnonymous]

        public ActionResult Details(int id = 0)
        {
            Post post = db.Posts.Find(id);
            ViewData["idpost"]=id;
           /* var post2 =db.Posts.Select(x => new { x.Comments, x.Titl }).
                Where(y => y.Titl.Contains("Chao")).
                Single() ;
            Session["Post"] = post2;*/
            if (post == null)
            {
                return HttpNotFound();
            }
            return View(post);
        }

        //
        // GET: /Posts/Create

        public ActionResult Create()
        {
            ViewBag.UserProfileUserId = new SelectList(db.UserProfiles, "UserId", "UserName");
            return View();
        }

        //
        // POST: /Posts/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Post post, string content)
        {
            if (ModelState.IsValid)
            {
                post.DateCreated = DateTime.Now;
                int userid=db.UserProfiles.Select(x=>new{x.UserId,x.UserName}).
                    Where(y=>y.UserName==User.Identity.Name).Single().UserId;
                //tao cac list Tag
                List<Tag> Tags = new List<Tag>();
                //Tach cac Tag theo dau ,
                string[] TagContent = content.Split(',');
                //Lap cac Tag vua tach
                foreach(string item in TagContent)
                {
                    //tim xem Tag content da co chua
                    Tag tagExits = null;
                    var ListTag = db.Tags.Where(y => y.Content.Equals(item));
                    if (ListTag.Count() > 0)
                    {
                        //neu co roi thi add them
                        tagExits = ListTag.First();
                        tagExits.Posts.Add(post);
                    }
                    else
                    {
                        //neu chua co thi tao moi
                        tagExits = new Tag();
                        tagExits.Content = item;
                        tagExits.Posts = new List<Post>();
                        tagExits.Posts.Add(post);
                    }
                    //add list cac Tag
                    Tags.Add(tagExits);
                }
                //Gan list Tag cho Post
                post.Tags = Tags;

                post.UserProfileUserId = userid;
                db.Posts.Add(post);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.UserProfileUserId = new SelectList(db.UserProfiles, "UserId", "UserName", post.UserProfileUserId);
            return View(post);
        }

        //
        // GET: /Posts/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Post post = db.Posts.Find(id);
            if (post == null)
            {
                return HttpNotFound();
            }
            ViewBag.UserProfileUserId = new SelectList(db.UserProfiles, "UserId", "UserName", post.UserProfileUserId);
            return View(post);
        }

        //
        // POST: /Posts/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Post post)
        {
            if (ModelState.IsValid)
            {
                db.Entry(post).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.UserProfileUserId = new SelectList(db.UserProfiles, "UserId", "UserName", post.UserProfileUserId);
            return View(post);
        }

        //
        // GET: /Posts/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Post post = db.Posts.Find(id);
            if (post == null)
            {
                return HttpNotFound();
            }
            return View(post);
        }

        //
        // POST: /Posts/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Post post = db.Posts.Find(id);
            db.Posts.Remove(post);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Blog5_t2/Blog5_t2/Controllers/TagsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Blog5_t2.Models;

namespace Blog5_t2.Controllers
{
    public class TagsController : Controller
    {
        private BlogDbContext db = new BlogDbContext();

        //
        // GET: /Tags/

        public ActionResult Index()
        {
            return View(db.Tags.ToList());
        }

        //
        // GET: /Tags/Details/5

        public ActionResult Details(int id = 0)
        {
            Tag tag = db.Tags.Find(id);
            if (tag == null)
            {
                return HttpNotFound();
            }
            return View(tag);
        }

        //
        // GET: /Tags/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Tags/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Tag tag)
        {
            if (ModelState.IsValid)
            {
                db.Tags.Add(tag);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(tag);
        }

        //
        // GET: /Tags/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Tag tag = db.Tags.Find(id);
            if (tag == null)
            {
                return HttpNotFound();
            }
            return View(tag);
        }

        //
        // POST: /Tags/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Tag tag)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tag).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tag);
        }

        //
        // GET: /Tags/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Tag tag = db.Tags.Find(id);
            if (tag == null)
            {
                return HttpNotFound();
            }
            return View(tag);
        }

        //
        // POST: /Tags/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Tag tag = db.Tags.Find(id);
            db.Tags.Remove(tag);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
        //
        //GET:/Tag/Search
        public ActionResult Search(int id=0)
        {
            return View();
        }
        //
        //POST:/Tag/Search
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Search(Tag tag, string content)
        {
            List<Post> posts = new List<Post>();
            string TagContent = content;
            Tag tagExits = null;
            foreach (var stag in db.Tags)
            {
                if (stag.Content == content)
                {
                    tagExits = stag;
                    break;
                }
            }
            return RedirectToAction("Searched/" + tagExits.ID);
        }
        //
        //GET:/Tag/Searched
        public ActionResult Searched(int id=0)
        {
            Tag tag = db.Tags.Find(id);
            if(tag==null)
            {
                return HttpNotFound();

            }
            return View(tag);
        }

    }
}

Blog5_t2/Blog5_t2/Views/Tags/Create.cshtml
@model Blog5_t2.Models.Tag

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Tag</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.Content)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Content)
            @Html.ValidationMessageFor(model => model.Content)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Blog5_t2/Blog5_t2/Views/Tags/Delete.cshtml
@model Blog5_t2.Models.Tag

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>Tag</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Content)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Content)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

Blog5_t2/Blog5_t2/Views/Tags/Details.cshtml
@model Blog5_t2.Models.Tag

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>Tag</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Content)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Content)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Blog5_t2/Blog5_t2/Views/Tags/Edit.cshtml
@model Blog5_t2.Models.Tag

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Tag</legend>

        @Html.HiddenFor(model => model.ID)

        <div class="editor-label">
            @Html.LabelFor(model => model.Content)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Content)
            @Html.ValidationMessageFor(model => model.Content)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Blog5_t2/Blog5_t2/Views/Tags/Index.cshtml
@model IEnumerable<Blog5_t2.Models.Tag>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Content)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Content)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID })
        </td>
    </tr>
}

</table>

Blog5_t2/Blog5_t2/Views/Tags/Search.cshtml
@model Blog5_t2.Models.Tag

@{
    ViewBag.Title = "Search";
}

<h2>Search post(s) by tag(s)</h2>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>Tag </legend>
        <div class="editor-field">
            @Html.EditorFor(model =>new Blog5_t2.Models.Tag().Content)
            @Html.ValidationMessageFor(model=>new Blog5_t2.Models.Tag().Content)
        </div>
        <p>
            <input type="submit" value="Search" />
        </p>
        </fieldset>
}

Blog5_t2/Blog5_t2/Views/Tags/Searched.cshtml
@model Blog5_t2.Models.Tag

@{
    ViewBag.Title = "Searched";
}

<h2>Searched</h2>
<fieldset>
    <legend>Post</legend>
    <p>Post Title: </p>
    @foreach (var post in Model.Posts)
    {
        @Html.ActionLink("" + post.Titl, "Details/" +post.ID, "Posts")<br />
    }
</fieldset>
<p>
    @Html.ActionLink("Back to Search", "Search")
</p>